### PR TITLE
Added Azure Data Lake Gen 2 provider.

### PR DESCRIPTION
**Pull request by richardoliverpearce**
Hi Ivan,

I've applied the changes to the v7 branch. The provider's integration tests and unit tests pass after a few changes.

Thanks

Richard

### CODE REVIEW

**Comment by aloneguid** [comment]
Thanks Richard, I'm going through this atm.

**Comment by richardoliverpearce** [comment]
Awesome thanks

**Comment by aloneguid** [comment]
Hey Richard, just setting up test rig for Gen2, I've added service principal as an owner of Gen2 account, also added explicitly as an owner of a test filesystem, but still getting an error below. Anything I need to do?

```
Message: Storage.Net.Microsoft.Azure.DataLakeGen2.Store.Gen2.Models.DataLakeGen2Exception : Exception occurred during call to Data Lake Gen 2 Rest API.
---- System.Net.Http.HttpRequestException : Response status code does not indicate success: 403 (This request is not authorized to perform this operation using this permission.).

```

**Comment by richardoliverpearce** [comment]
Hi Ivan, you'll either want the Storage Blob Data Owner IAM role (which is full access to all file systems in the data lake), or if you want to limit access, read, write, execute and all defaults at posix level on the testfilesystemclientsecret file system should be enough. Thanks

**Comment by richardoliverpearce** [comment]
Have you been able to run the shared access key test fixture?

**Comment by aloneguid** [comment]
Thanks Richard, SAS key authentication is working, it's only client id / secret fails whatever permissions I grant.

**Comment by aloneguid** [comment]
it's working now by bad, "Storage Blob Data Owner" role did the trick.

**Comment by aloneguid** [comment]
I've moved the code under main DataLake project, so it contains both Gen1&Gen2 implementations. Thank you!

**Comment by richardoliverpearce** [comment]
Awesome thanks!!

**Pull request merged**
