### PR TITLE
Add SFtp support and blob move capabilities

### PR DESCRIPTION
**Pull request by nenitiko**
I consider this a long shot since this lacking unit tests :/ ... the code works and it's being used in production now.  Move semantics are an extension to the base Blob interface and does not support moving from blob storage to a different blob storage, only supported for both FTP and SFTP providers as written.

### CODE REVIEW

**Comment by aloneguid** [comment]
@nenitiko thanks for contributing, there are some conflicts, can I help with anything? By the way you should raise PR against `develop` branch - this should have been offered by default, unless you've forked from an older version. Master is for releases only, CI generates release notes etc. from master commits.

**Comment by aloneguid** [comment]
I can rebase to `develop` later once you're ready though, so no worries.

**Comment by thijsgelton** [comment]
What is the status of this PR? Right now I created a fork of @nenitiko 's repository, because we needed SFTP as well. I would prefer it to be packaged with @aloneguid your repo. If there need to be thorough unit testing present, I could create them. Then you could merge 👍

**Comment by nenitiko** [comment]
I'm creating a new pull requests forked from the latest version and using the dev branch

**Pull request closed without merging**
